name: Build LibreCAD on musl

on:
  push:
    branches:
      - LibreCAD-up
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl-full
      options: --privileged
      volumes:
        - /dev:/dev

    steps:
      - name: Prepare container
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash curl git git-lfs
          useradd -G xbuilder -M builder

      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Prepare masterdir
        run: |
          chown -R builder:builder .
          sudo -Eu builder common/travis/set_mirror.sh
          sudo -Eu builder common/travis/prepare.sh
          common/travis/fetch-xtools.sh

      - name: Build LibreCAD
        run: |
          sudo -Eu builder ./xbps-src pkg LibreCAD

      - name: Find and set XBPS package path
        id: verify_xbps
        run: |
          XBPS_FILE=$(find hostdir/binpkgs -name "LibreCAD-*.xbps" | head -n 1)
          if [ -z "$XBPS_FILE" ]; then
            echo "No LibreCAD xbps package found!"
            exit 1
          fi
          echo "xbps_path=$XBPS_FILE" >> $GITHUB_OUTPUT
          echo "Found XBPS package at: $XBPS_FILE"

      - name: Upload to Git LFS with PAT
        run: |

          # clone my github repository
          git clone https://x-access-token:${{ secrets.PERSONAL_PAT}}@github.com/kpnc0/void-packages-binaries.git binary-repo

          git lfs install
          git lfs track "*.xbps"
          cd binary-repo

          mkdir -p packages
          cp ../${{ steps.verify_xbps.outputs.xbps_path }} packages/

          git config user.email "bot@voidlinux.org"
          git config user.name "Void Bot"

          git add -f packages/*.xbps
          git commit -m "Add LibreCAD package from ${{ github.sha }}"
          git push -f origin master
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT}}
